name: Build itch zip

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: false
        default: 'main'
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Setup Node (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ensure zip is available
        run: sudo apt-get update && sudo apt-get install -y zip

      # Install deps from package.json in /frontend (no lockfile required)
      - name: Install deps
        working-directory: frontend
        run: npm install --no-audit --no-fund

      - name: Build (Vite)
        working-directory: frontend
        env:
          NODE_ENV: production
          VITE_API_BASE: ${{ vars.VITE_API_BASE || '' }}
        run: npm run build

      # Zip the *contents* of dist so index.html is at the root of the zip
      - name: Create itch zip
        working-directory: frontend/dist
        run: zip -r ../../exit-or-die.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exit-or-die-zip
          path: exit-or-die.zip