name: Build itch zip

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: false
        default: 'main'
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json  # harmless if missing

      - name: Ensure zip is available
        run: sudo apt-get update && sudo apt-get install -y zip

      # We DON'T require a lock file. Install from package.json in frontend/
      - name: Install deps
        working-directory: frontend
        run: npm install

      - name: Build (Vite)
        working-directory: frontend
        env:
          NODE_ENV: production
          VITE_API_BASE: ${{ vars.VITE_API_BASE || '' }}
        run: npm run build

      - name: Create itch zip (index.html at root of zip)
        working-directory: frontend/dist
        run: zip -r ../../exit-or-die.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exit-or-die-zip
          path: exit-or-die.zip